name: Deploy to Development
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
      - name: Run deployment script on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEV_EC2_USER }}@${{ secrets.DEV_EC2_HOST }} "bash /home/ec2-user/deployment-scripts/backend-deployment-script.sh"
      - name: Notify success
        if: success()
        run: echo "Development deployment was successful!"
      - name: Notify failure
        if: failure()
        run: echo "Development deployment failed. Check logs."
